
version: '3.8'

services:
  db:
    image: timescale/timescaledb:2.18.1-pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_subnet_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/home/postgres/pgdata/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
