-- pgmigrations:disable-transaction

DROP MATERIALIZED VIEW IF EXISTS hourly_stats CASCADE;
DROP MATERIALIZED VIEW IF EXISTS minute_stats CASCADE;
DROP MATERIALIZED VIEW IF EXISTS hourly_stats_discrete CASCADE;
DROP MATERIALIZED VIEW IF EXISTS minute_stats_discrete CASCADE;
